<?php
/*

 Block parameters;
    title   - Block title
    class   - Custom class name for stylesheet, optional
    subline - Subline, HTML, optional
    content - block contents:
            string  - regular content
            array   - compound content:
                []  => Element Title (or tab title)
                       Element content

 Regular block: header + body
 |=============================================================================|
 | Block Title                                                                 |
 |-----------------------------------------------------------------------------|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block w/o title
 |=============================================================================|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block with subline
 |=============================================================================|
 | Block Title                             (Subline: link | link | link | more)|
 |-----------------------------------------------------------------------------|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block with tabs
 |=============================================================================|
 | | tab | tab | tab | tab | tab |
 |------------------------------------------------------------------------------|
 | Block content of first tab ...                                                |
 | Block content of first tab ...                                                |
 | Block content of first tab ...                                                |
 |=============================================================================|

 */
?>
<?php
// Render heading and body
if (is_array($block['content'])) {
    // Tab block
    $class = sprintf('panel panel-default pi-panel-tab %s', $block['class']);
    $heading = sprintf('<div class="pi-block-tabtitle"><h2><i class="fa fa-th-list"></i> %s</h2></div>', $block['title']);
    $heading .= '<ul class="pi-panel-tab-indicators"><li class="pi-block-tabinfo">شاخه ها <i class="fa fa-angle-left"></i></li>';
    $body = '<div class="panel-body tab-content">';
    foreach ($block['content'] as $key => $item) {
        $heading .= sprintf(
            '<li class="%s"><a href="%s" data-toggle="tab" data-target="#panel-%s">%s</a>',
            $key == 0 ? 'active' : '',
            $item['link'] ? $item['link'] : '#',
            $block['id'] . $key,
            $item['caption']
        );
        $body .= sprintf(
            '<div class="tab-pane%s" id="panel-%s">%s</div>',
            $key == 0 ? ' active' : '',
            $block['id'] . $key,
            $item['content']
        );
    }
    $heading .= '</ul>';
    $body .= '</div>';
    $heading = sprintf('<div class="panel-heading">%s</div>', $heading);
} else {
    // Check subline
    if (!empty($block['subline'])) {
        $subline = sprintf(
            '<div class="pi-panel-subline pull-left text-left"> <span>/</span> <a href="%s">آرشیو</a></div>',
            $block['subline']
        );
    } else {
        $subline = '';
    }
    // Check fullsize
    if ($block['body_fullsize']) {
        $class = 'pi-block';
        if (!$block['title_hidden']) {
            $heading = sprintf('<div class="pi-block-title clearfix"><h2 class="pull-left text-left"><i class="fa %s"></i> %s</h2>%s</div>', $block['class'], $block['title'], $subline);
        }
        $body = sprintf('<div class="pi-block-content">%s</div>', $block['content']);
    } else {
        $class = sprintf('panel panel-default %s', $block['class']);
        if (!$block['title_hidden']) {
            $heading = sprintf('<div class="panel-heading"><h2 class="panel-title">%s</h2></div>', $heading);
        }
        $body = sprintf('<div class="panel-body">%s</div>', $block['content']);
    }
}
?>
<div id="block-<?php echo $block['id']; ?>" class="<?php echo $class; ?>">
    <?php
    echo $heading;
    echo $body;
    ?>
</div>